package com.phcarvalho.model.corba.server;


/**
* com/phcarvalho/model/corba/server/ServerServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharingIDL.idl
* Segunda-feira, 14 de Outubro de 2019 22h17min22s BRT
*/

public interface ServerServiceOperations 
{
  void sendSharedFileList(com.phcarvalho.model.corba.SharedFileList sharedFileList);
  com.phcarvalho.model.corba.SharedFileList search(String name);
} // interface ServerServiceOperations
