package com.phcarvalho.model.corba.server;


/**
* com/phcarvalho/model/corba/server/ServerServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharingIDL.idl
* Segunda-feira, 14 de Outubro de 2019 22h17min22s BRT
*/

public abstract class ServerServicePOA extends org.omg.PortableServer.Servant
 implements com.phcarvalho.model.corba.server.ServerServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sendSharedFileList", new Integer (0));
    _methods.put ("search", new Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // com/phcarvalho/model/corba/server/ServerService/sendSharedFileList
       {
         com.phcarvalho.model.corba.SharedFileList sharedFileList = com.phcarvalho.model.corba.SharedFileListHelper.read (in);
         this.sendSharedFileList (sharedFileList);
         out = $rh.createReply();
         break;
       }

       case 1:  // com/phcarvalho/model/corba/server/ServerService/search
       {
         String name = in.read_string ();
         com.phcarvalho.model.corba.SharedFileList $result = null;
         $result = this.search (name);
         out = $rh.createReply();
         com.phcarvalho.model.corba.SharedFileListHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:com/phcarvalho/model/corba/server/ServerService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerService _this() 
  {
    return ServerServiceHelper.narrow(
    super._this_object());
  }

  public ServerService _this(org.omg.CORBA.ORB orb) 
  {
    return ServerServiceHelper.narrow(
    super._this_object(orb));
  }


} // class ServerServicePOA
