package com.phcarvalho.filesharing;


/**
* com/phcarvalho/filesharing/ClientPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientFileSharingIDL.idl
* Domingo, 13 de Outubro de 2019 23h48min09s BRT
*/

public abstract class ClientPOA extends org.omg.PortableServer.Servant
 implements ClientOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("downloadSharedFile", new Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // com/phcarvalho/filesharing/Client/downloadSharedFile
       {
         String name = in.read_string ();
         com.phcarvalho.filesharing.SharedFile $result = null;
         $result = this.downloadSharedFile (name);
         out = $rh.createReply();
         com.phcarvalho.filesharing.SharedFileHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:com/phcarvalho/filesharing/Client:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Client _this() 
  {
    return ClientHelper.narrow(
    super._this_object());
  }

  public Client _this(org.omg.CORBA.ORB orb) 
  {
    return ClientHelper.narrow(
    super._this_object(orb));
  }


} // class ClientPOA
