package com.phcarvalho.filesharing;


/**
* com/phcarvalho/filesharing/Client.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientFileSharingIDL.idl
* Domingo, 13 de Outubro de 2019 23h48min09s BRT
*/

public interface Client extends ClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Client
