package com.phcarvalho.filesharing;

/**
* com/phcarvalho/filesharing/ClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JavaFileSharingIDL.idl
* Domingo, 13 de Outubro de 2019 22h52min48s BRT
*/

public final class ClientHolder implements org.omg.CORBA.portable.Streamable
{
  public Client value = null;

  public ClientHolder ()
  {
  }

  public ClientHolder (Client initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientHelper.type ();
  }

}
