package com.phcarvalho.filesharing;


/**
* com/phcarvalho/filesharing/ClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientFileSharingIDL.idl
* Domingo, 13 de Outubro de 2019 23h48min09s BRT
*/

public interface ClientOperations 
{
  com.phcarvalho.filesharing.SharedFile downloadSharedFile(String name);
} // interface ClientOperations
