package com.phcarvalho.filesharing;

/**
* com/phcarvalho/filesharing/ServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JavaFileSharingIDL.idl
* Domingo, 13 de Outubro de 2019 22h52min48s BRT
*/

public final class ServerHolder implements org.omg.CORBA.portable.Streamable
{
  public Server value = null;

  public ServerHolder ()
  {
  }

  public ServerHolder (Server initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServerHelper.type ();
  }

}
