package com.phcarvalho.filesharing;

/**
* com/phcarvalho/filesharing/SharedFileListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JavaFileSharingIDL.idl
* Domingo, 13 de Outubro de 2019 22h52min48s BRT
*/

public final class SharedFileListHolder implements org.omg.CORBA.portable.Streamable
{
  public SharedFileList value = null;

  public SharedFileListHolder ()
  {
  }

  public SharedFileListHolder (SharedFileList initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SharedFileListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SharedFileListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SharedFileListHelper.type ();
  }

}
