package com.phcarvalho.filesharing;


/**
* com/phcarvalho/filesharing/SharedFileList.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JavaFileSharingIDL.idl
* Domingo, 13 de Outubro de 2019 22h52min48s BRT
*/

public final class SharedFileList implements org.omg.CORBA.portable.IDLEntity
{
  public SharedFile sharedFileList[] = null;

  public SharedFileList ()
  {
  } // ctor

  public SharedFileList (SharedFile[] _sharedFileList)
  {
    sharedFileList = _sharedFileList;
  } // ctor

} // class SharedFileList
