package com.phcarvalho.filesharing;

/**
* com/phcarvalho/filesharing/SharedFileHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JavaFileSharingIDL.idl
* Domingo, 13 de Outubro de 2019 22h52min48s BRT
*/

public final class SharedFileHolder implements org.omg.CORBA.portable.Streamable
{
  public SharedFile value = null;

  public SharedFileHolder ()
  {
  }

  public SharedFileHolder (SharedFile initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SharedFileHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SharedFileHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SharedFileHelper.type ();
  }

}
