package com.phcarvalho.filesharing;


/**
* com/phcarvalho/filesharing/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientFileSharingIDL.idl
* Domingo, 13 de Outubro de 2019 23h48min09s BRT
*/

public final class User implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String host = null;
  public short port = (short)0;

  public User ()
  {
  } // ctor

  public User (String _name, String _host, short _port)
  {
    name = _name;
    host = _host;
    port = _port;
  } // ctor

} // class User
