package com.phcarvalho.model.corba;


/**
* com/phcarvalho/model/corba/SharedFileList.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharingIDL.idl
* Segunda-feira, 14 de Outubro de 2019 22h17min22s BRT
*/

public final class SharedFileList implements org.omg.CORBA.portable.IDLEntity
{
  public SharedFile sharedFileList[] = null;

  public SharedFileList ()
  {
  } // ctor

  public SharedFileList (SharedFile[] _sharedFileList)
  {
    sharedFileList = _sharedFileList;
  } // ctor

} // class SharedFileList
