package com.phcarvalho.model.corba;


/**
* com/phcarvalho/model/corba/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharingIDL.idl
* Segunda-feira, 14 de Outubro de 2019 22h17min22s BRT
*/

public final class User implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String host = null;
  public short port = (short)0;

  public User ()
  {
  } // ctor

  public User (String _name, String _host, short _port)
  {
    name = _name;
    host = _host;
    port = _port;
  } // ctor

} // class User
