package com.phcarvalho.model.corba.client;


/**
* com/phcarvalho/model/corba/client/ClientServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharingIDL.idl
* Segunda-feira, 14 de Outubro de 2019 22h17min22s BRT
*/

public interface ClientServiceOperations 
{
  com.phcarvalho.model.corba.SharedFile downloadSharedFile(String name);
} // interface ClientServiceOperations
