package com.phcarvalho.model.corba.client;


/**
* com/phcarvalho/model/corba/client/ClientServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharingIDL.idl
* Segunda-feira, 14 de Outubro de 2019 22h17min22s BRT
*/

public abstract class ClientServicePOA extends org.omg.PortableServer.Servant
 implements com.phcarvalho.model.corba.client.ClientServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("downloadSharedFile", new Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // com/phcarvalho/model/corba/client/ClientService/downloadSharedFile
       {
         String name = in.read_string ();
         com.phcarvalho.model.corba.SharedFile $result = null;
         $result = this.downloadSharedFile (name);
         out = $rh.createReply();
         com.phcarvalho.model.corba.SharedFileHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:com/phcarvalho/model/corba/client/ClientService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientService _this() 
  {
    return ClientServiceHelper.narrow(
    super._this_object());
  }

  public ClientService _this(org.omg.CORBA.ORB orb) 
  {
    return ClientServiceHelper.narrow(
    super._this_object(orb));
  }


} // class ClientServicePOA
